[project]
name = "lam"
version = "0.1.0"
requires-python = ">=3.10, <3.13"
dependencies = [
    "easydict~=1.13",
    "fasttext-wheel~=0.9.2",
    "ipython~=8.20.0",
    "lmdb~=1.4.1",
    "matplotlib>=3.7.5",
    "pyarrow>=19.0.1",
    "pykalman~=0.9.7",
    "transformers==4.44.1",
]
