default:
  logger:
    log_level: "INFO"
  service:
    host: "0.0.0.0"
    port: 8282
    cert_file: "ssl_certs/localhost.crt"
    cert_key: "ssl_certs/localhost.key"
  chat_engine:
    model_root: "models"
    concurrent_limit: 2
    handler_search_path:
      - "src/handlers"
    handler_configs:
      RtcClient:
        turn_config:
          turn_provider: "turn_server"
          urls: ["turn:101.201.29.97:3478", "turns:101.201.29.97:5349"]
          username: "openavatar"
          credential: "asd123"
          realm: "turn.101-201-29-97.turnserver"
        module: client/rtc_client/client_handler_rtc
        # max time a session will last for
        connection_ttl: 900
      SileroVad:
        module: vad/silerovad/vad_handler_silero
        speaking_threshold: 0.4
        start_delay: 2400
        end_delay: 16000
        buffer_look_back: 14400
        speech_padding: 1200
      SenseVoice:
        enabled: True
        module: asr/sensevoice/asr_handler_sensevoice
        model_name: "iic/SenseVoiceSmall"
      CosyVoice:
        enabled: True
        module: tts/bailian_tts/tts_handler_cosyvoice_bailian
        voice: "longxiaochun"
        model_name: "cosyvoice-v1"
        # default=os.getenv("DASHSCOPE_API_KEY")
        # api_key: "" # default=os.getenv("DASHSCOPE_API_KEY")
      LLMOpenAICompatible:
        enabled: True
        module: llm/openai_compatible/llm_handler_openai_compatible
        model_name: "qwen-vl-plus"
        enable_video_input: True # ensure your llm support video input
        history_length: 20
        # model_name: "gemini-2.0-flash"
        system_prompt: "
          ### 角色与任务
          你是中海高科AI心理师，专为青少年提供温暖的倾听。你的核心任务是成为一个优秀的倾听者，而不是一个说教的老师。
          
          ### 对话核心原则
          1.  **共情与简洁**: 你的回答要温暖、有同理心，但同时要**简洁自然，像聊天一样**。一次只围绕一个焦点进行回应，鼓励用户继续说下去。
          2.  **倾听与建议**: 你的首要工作是倾听和理解对方的感受。多用“听起来这让你觉得...”来确认他的情绪，并给出解决方案。
          3.  **明确AI边界**: 你不是医生，**绝不能进行心理诊断**或提供医疗建议。要让用户知道你是一个AI伙伴。
          
          ### 【最高优先级：安全红线】
          如果用户明确表达**自杀、自残或伤害他人**的想法，你必须**立即中断**当前对话，并直接发送以下固定内容，不要添加任何多余的话：
          
          “听到你这么说，我非常担心。你的安全是最重要的事。我是一个AI，能做的有限，但请相信，有很多人可以帮助你。请立即联系他们：
          - **全国希望24小时热线：400-161-9995**
          - **情况紧急请拨打：110 或 120**
          他们是专业的，能给你现在最需要的支持。请一定联系他们。”
          
          "  
        api_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
        # api_url: 'http://127.0.0.1:11434/v1' # ollama
        # api_url: 'https://generativelanguage.googleapis.com/v1beta/openai/'
        # api_key: "" # default=os.getenv("DASHSCOPE_API_KEY")
      LiteAvatar:
        module: avatar/liteavatar/avatar_handler_liteavatar
        avatar_name: 20250612/P1-64AzfrJY037WpS69RiUMw  
        fps: 10
        debug: false
        enable_fast_mode: false
        use_gpu: false
