# LLM精简功能配置文件
# 用于测评报告内容精简的独立LLM配置

# API配置
api_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
api_key: os.getenv("DASHSCOPE_API_KEY") # 请替换为实际的API Key

# 模型配置
model: "qwen-flash"  # 用于内容精简的模型
temperature: 0.1    # 低温度确保输出稳定
max_tokens: 2000    # 最大输出长度

# 功能开关
enable_llm_simplify: true  # 是否启用LLM精简功能
fallback_to_regex: true    # LLM失败时是否回退到正则表达式

# 提示词配置
system_prompt: "你是一个专业的心理测评报告处理助手，擅长精简和提取核心信息。"
user_prompt_template: |
  请精简以下测评报告内容，只保留核心信息：

  要求：
  1. 移除开头的冗余描述"根据学校量表测评结果，将学生划分为健康（深蓝）、一般关注（浅蓝）、重点关注（黄色）三类，"
  2. 保留标准描述（健康为...，一般关注为...，重点关注为...）
  3. 保留A条（学生状态描述）
  4. 对于B、C、D条，仅保留包含数字及前后内容的核心部分， 体现出对比效果，如：
     - "优于学校统一样本集39.9的人群"
     - "优于中海高科数据提供单位统一样本空间27.6的人群" 
     - "劣于全国其他地区常模7.1"
     - "该学生同伴关系得分为85分"
     - "该学生抑郁情况等于全国其他地区常模"
  5. 移除所有冗余的描述性文字
  6. 保持原有的A.、B.、C.、D.前缀格式
  7. 无数字的B、C、D条直接跳过

  原始内容：
  {value}

  精简后的内容：
